// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'use yourapi here',
    appId: 'use yourapi here',
    messagingSenderId: '278633099237',
    projectId: 'testapp1-a3e57',
    authDomain: 'testapp1-a3e57.firebaseapp.com',
    storageBucket: 'testapp1-a3e57.firebasestorage.app',
    measurementId: 'G-JYWMHH4HWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'use yourapi here4',
    appId: 'use yourapi here',
    messagingSenderId: '278633099237',
    projectId: 'testapp1-a3e57',
    storageBucket: 'testapp1-a3e57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'use yourapi here',
    appId: 'use yourapi here',
    messagingSenderId: '278633099237',
    projectId: 'testapp1-a3e57',
    storageBucket: 'testapp1-a3e57.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'use yourapi here',
    appId: 'use yourapi here',
    messagingSenderId: '278633099237',
    projectId: 'testapp1-a3e57',
    storageBucket: 'testapp1-a3e57.firebasestorage.app',
    iosBundleId: 'com.example.stockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'use yourapi here',
    appId: 'use yourapi here',
    messagingSenderId: '278633099237',
    projectId: 'testapp1-a3e57',
    authDomain: 'testapp1-a3e57.firebaseapp.com',
    storageBucket: 'testapp1-a3e57.firebasestorage.app',
    measurementId: 'G-VQFWMSN884',
  );
}
